apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: canary
spec:
  generators:
  - git:
      repoURL: https://github.com/danf425/appsets-argocd-rollouts
      revision: HEAD
      files:
      - path: "cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster_name}}-canary'
      labels:
        harness.io/envRef: '{{environment}}'
        harness.io/serviceRef: '{{harness_service}}'
        harness.io/buildRef: '{{image_tag}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/danf425/appsets-argocd-rollouts
        targetRevision: HEAD
        path: "base"
        kustomize:
          images:
          - argoproj/rollouts-demo:{{image_tag}}
      destination:
        server: '{{server_address}}'
        namespace: 'canary-{{environment}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
